var AWESOME=function(){return{ready:function(a,b){var c,e,d=function(k){if(k&&k.type=="DOMContentLoaded")f();else if(k&&k.type=="load")f();else if(document.readyState)if(/loaded|complete/.test(document.readyState))f();else if(document.documentElement.doScroll){try{c||document.documentElement.doScroll("left")}catch(g){return}f()}},f=function(){if(!c){c=true;a.call(b||window);document.removeEventListener&&document.removeEventListener("DOMContentLoaded",d,false);document.onreadystatechange=null;window.onload=
null;clearInterval(e);e=null}};document.addEventListener&&document.addEventListener("DOMContentLoaded",d,false);document.onreadystatechange=d;e=setInterval(d,5);window.onload=d},log:function(a){typeof console!=="undefined"&&console.log(a)},cancelEvent:function(a){a=a||window.event;if(a.preventDefault)a.preventDefault();else a.returnValue=false},cancelPropagation:function(a){if(a.stopPropagation)a.stopPropagation();else a.cancelBubble=true},bind:function(a,b,c,e){if(!(typeof a=="undefined"||a==null)){e=
e||false;if(typeof a.length=="undefined")a=[a];for(var d=a.length;d--;)if(a[d].addEventListener)a[d].addEventListener(b,c,e);else if(a.attachEvent)a[d].attachEvent("on"+b,c);else a[d]["on"+b]=c}},unbind:function(a,b,c,e){if(!(typeof a=="undefined"||a==null)){e=e||false;if(typeof a.length=="undefined")a=[a];for(var d=a.length;d--;)if(a[d].removeEventListener)a[d].removeEventListener(b,c,e);else if(a[d].detachEvent)a[d].detachEvent("on"+b,c);else a[d]["on"+b]=null}},fire:function(a,b,c,e){var d;if(document.createEventObject){d=
document.createEventObject();return a.fireEvent("on"+b,d)}c=c||false;e=e||true;d=document.createEvent("HTMLEvents");d.initEvent(b,c,e);return!a.dispatchEvent(d)},submit:function(a){if(typeof a!="undefined"){a.submit();return false}},hover:function(a,b,c,e){if(typeof a!="undefined"){c=c||null;this.bind(a,"mouseover",b,e);c&&this.bind(a,"mouseout",c,e)}},hasClass:function(a,b){return-1!=a.className.split(" ").indexOf(b)},addClass:function(a,b){this.hasClass(a,b)||(a.className+=" "+b)},removeClass:function(a,
b){if(this.hasClass(a,b))var c=a.className.split(" ");c.splice(c.indexOf(b),1);var e=c.length;for(a.className="";e--;)a.className+=c[e]+" "},getId:function(a){return document.getElementById(a)},getTag:function(a,b){b=b||document;a=a||"*";return b.getElementsByTagName(a)},getClass:function(a,b,c){var e=[];b=this.getTag(c,b);c=b.length;a=RegExp("(^|\\s)"+a+"(\\s|$)");for(var d=0,f=0;d<c;++d)if(a.test(b[d].className)){e[f]=b[d];f++}return e},toCamelCase:function(a){var b=a.split("-");if(b.length==1)return b[0];
a=a.indexOf("-")==0?b[0].charAt(0).toUpperCase()+b[0].substring(1):b[0];for(var c=1,e=b.length;c<e;++c){var d=b[c];a+=d.charAt(0).toUpperCase()+d.substring(1)}return a},style:function(a,b,c){if(a)b=this.toCamelCase(b);if(c=c||null)if(b=="opacity"){a.style.filter="alpha(opacity="+c*100+")";a.style.opacity=c}else{b=this.toCamelCase(b);a.style[b]=c}else if((c=document.defaultView)&&c.getComputedStyle)return c.getComputedStyle(a,"")[b]||null;else{if(b=="opacity"){a=a.filters("alpha").opacity;return isNaN(a)?
1:a?a/100:0}return a.currentStyle[b]||null}},docHeight:function(){var a=document;return Math.max(Math.max(a.body.scrollHeight,a.documentElement.scrollHeight),Math.max(a.body.offsetHeight,a.documentElement.offsetHeight),Math.max(a.body.clientHeight,a.documentElement.clientHeight))},docWidth:function(){var a=document;return Math.max(a.body.clientWidth,a.documentElement.clientWidth)},attr:function(a,b,c){if(c=c||null)a.setAttribute(b,c);else{c=a.attributes.length;a=a.getAttribute(b)||a[b]||null;if(!a)for(;c--;)if(b[c].nodeName===
b)a=b[i].nodeValue;return a}},encodeHTML:function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")},text:function(a,b){if(typeof a!="undefined")if(b){if(a.innerText!="undefined")a.innerText=b;a.textContent=b}else return a.innerText||a.textContent},prepend:function(a,b){b.insertBefore(a,b.childNodes[0])},append:function(a,b){b.appendChild(a)},before:function(a,b){b.parentNode.insertBefore(a,b)},after:function(a,b){b.parentNode.insertBefore(a,b.nextSibling)},
swap:function(a,b){a.parentNode.replaceChild(b,a)},remove:function(a){if(!a)return false;"length"in a||(a=[a]);for(var b=0,c=a.length;b<c;++b){if(!a[b].parentNode)return false;a[b].parentNode.removeChild(a[b])}},create:function(a){return document.createElement(a)},createCookie:function(a,b,c){var e="";if(c){e=new Date;e.setTime(e.getTime()+c*24*60*60*1E3);e="; expires="+e.toGMTString()}document.cookie=a+"="+b+e+";"},eraseCookie:function(a){this.createCookie(a,"",-1)},readCookie:function(a){if(document.cookie.length>
0){var b=document.cookie.indexOf(a+"=");if(b!=-1){b=b+a.length+1;a=document.cookie.indexOf(";",b);if(a==-1)a=document.cookie.length;return unescape(document.cookie.substring(b,a))}}return null},greatest:function(a){var b=Math;return b.max.apply(b,a)},smallest:function(a){var b=Math;return b.min.apply(b,a)},getRandom:function(a,b){var c=Math;return a?c.floor(c.random()*(b-a+1))+a:c.round(c.random())},getUrlVars:function(){for(var a=[],b,c=window.location.href.slice(window.location.href.indexOf("?")+
1).split("&"),e=c.length,d=0;d<e;++d){b=c[d].split("=");a.push(b[0]);a[b[0]]=b[1]}return a},serialize:function(a){for(var b=["input","select","textarea"],c=b.length,e=[],d=[],f={},k=[],g=0;g<c;++g){k=a.getElementsByTagName(b[g]);for(var j=k.length,l=0;l<j;++l)e.push(k[l])}b=e.length;for(g=0;g<b;++g){a=e[g];switch(e[g].nodeName.toLowerCase()){case "input":switch(a.type){case "text":d.push(a);break;case "hidden":d.push(a);break;case "password":d.push(a);break;case "checkbox":a.checked&&d.push(a);break;
case "radio":a.checked&&d.push(a)}break;case "select":d.push(a);break;case "textarea":d.push(a)}}e=d.length;for(g=0;g<e;++g){a=d[g];if(f.hasOwnProperty(a.name))if(typeof f[a.name]=="string")f[a.name]=[f[a.name],a.value.toString()];else f[a.name].push(a.value.toString());else f[a.name]=a.value}return f},formatParams:function(a){if(a==null)return"";var b=[];for(p in a)a.hasOwnProperty(p)&&b.push(encodeURIComponent(p)+"="+encodeURIComponent(a[p]));return b.join("&")},ajax:function(a){function b(j,l){var h=
d();if(h!=null){var m=new Date;h.open(j,l,true);j=="POST"&&h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");a.disguise||h.setRequestHeader("X-Requested-With","XMLHttpRequest");h.setRequestHeader("X-Request-Id",m.getTime());h.onreadystatechange=function(){switch(h.readyState){case 0:a.beforeSend();break;case 1:a.sendPrepared();break;case 2:a.afterSend();break;case 3:a.preComplete(h);break;case 4:if(h.status>=200&&h.status<300)a.complete(h);else h.status==0?a.complete(h):a.failure(h)}};
return h}}function c(j){j=b("GET",j+g.formatParams(a.data));j.send("");return j}function e(j){j=b("POST",j);j.send(g.formatParams(a.data));return j}function d(){if(typeof XMLHttpRequest!="undefined")return new XMLHttpRequest;try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(j){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(l){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(h){}try{return new ActiveXObject("Microsoft.XMLHTTP")}catch(m){}return null}var f={url:null,data:null,
type:"post",dataType:null,disguise:false,beforeSend:function(){},sendPrepared:function(){},afterSend:function(){},preComplete:function(){},complete:function(){},failure:function(){}};if(a)for(var k in f){if(typeof a[k]=="undefined")a[k]=f[k]}else a=f;if(a.url!=null){var g=this;switch(a.type.toUpperCase()){case "GET":c(a.url,a.data);break;case "POST":e(a.url,a.data)}}}}}();
